package ac.suza.ims.auth.entity;

public enum ModuleType {
    USER_MANAGEMENT,
    ROLE_MANAGEMENT,
    ORGANIZATION_MANAGEMENT,
    INNOVATION_MANAGEMENT,
    STARTUP_MANAGEMENT,
    FUNDING_MANAGEMENT,
    COMPETITION_MANAGEMENT,
    REPORT_MANAGEMENT,
    SYSTEM_SETTINGS
}
