package ac.suza.ims.auth.entity;

public enum RoleType {
    SUPER_ADMIN,
    INNOVATION_DIRECTOR,
    CENTRAL_INNOVATION_MANAGER,
    SCHOOL_INNOVATION_MANAGER,
    MENTOR,
    REVIEWER,
    INNOVATOR,
    INVESTOR,
    PUBLIC_VISITOR
}
